### ISSUE TITLE
DDlog generates funky code when given paths

### ISSUE THREAD

**Issue by Kixiron** [vmware/differential-datalog#1001]
If ddlog is run with an `-i` argument that's a relative path (e.g. `ddlog -i .\simple.dl`) it generates invalid code (mainly in the Cargo.toml but probably elsewhere)

Sample invalid code in Cargo.toml:
```toml
[package]
name = ".\simple.dl"

[lib]
name = ".\simple.dl"
```

I don't know if this is to do with Haskell's path handling or something else, but it makes code break
