### ISSUE TITLE
New module system breaks relative dependency paths

### ISSUE THREAD

**Issue by Kixiron** [vmware/differential-datalog#859]
If a ddlog program imports a dependency by a relative path, the copy+paste of said paths down the module tree will break the dependencies

```toml
# ddlog_main.toml
[dependencies.something]
path = "../../something"
```

That entry will be pasted into all generated sub-crates where the path is no longer valid, breaking said crates and being unable to compile
